VIC-13775: Don't drop breadcrumbs from DEV_ASSERT (#5283)
* Revert "Revert "VIC-13775: Don't drop breadcrumbs from DEV_ASSERT (#5263)""

This reverts commit 329a22f905e6d31d8577555ec3e7e6711de70f85.

* VIC-13775:  Add missing matrix_impl.h to coretech common tests

Object files that rely on matrix templates should include matrix_impl.h to instantiate methods as needed.

Fixes build error that occurs when linking release build without assertions:
{{
12:05:14] :	 [Step 5/14] Undefined symbols for architecture x86_64:
[12:05:14] :	 [Step 5/14]   "bool Anki::IsNearlyEqual<3ul, 3ul, float>(Anki::SmallMatrix<3ul, 3ul, float> const&, Anki::SmallMatrix<3ul, 3ul, float> const&, float)", referenced from:
[12:05:14] :	 [Step 5/14]       PoseTest_RotateBy_Test::TestBody() in coreTechCommonTests.cpp.o
[12:05:14] :	 [Step 5/14]   "Anki::SmallMatrix<3ul, 3ul, float>::GetColumn(unsigned long) const", referenced from:
[12:05:14] :	 [Step 5/14]       PoseTest_RotateBy_Test::TestBody() in coreTechCommonTests.cpp.o
[12:05:14] :	 [Step 5/14] ld: symbol(s) not found for architecture x86_64
}}