Tech Debt: Fix extraneous template keyword (#5361)
Remove unexpected 'template' keyword from non-templated method to appease Xcode 10.2.
It looks like the keyword is not appropriate because begin() is a method on a template class but not itself a templated method?

/Users/david/GitHub/victor/test/engine/testSurfaceClassifier.cpp:180:47: error: 'begin' following the 'template' keyword does not refer to
      a template [Semantic Issue]
      auto elementY = trainingLabels.template begin(); // probably don't need the .template here, but it looks cool :)
                                              ^
/Users/david/GitHub/victor/test/engine/testSurfaceClassifier.cpp:194:17: note: in instantiation of function template specialization
      'checkClassifier(Anki::Vector::RawPixelsClassifier &, const std::string &, const std::string &, float &, float, float)::(anonymous
      class)::operator()<cv::Mat_<int> >' requested here [Semantic Issue]
      fillPixels(positiveY, pixels, cv::Mat_<int>(trainingLabels));