VIC-2085 Harden linux binaries
Adds security flags via toolchains for Vicos and introduces a Mac OSX
toolchain for keeping configuration data together in a single file.

Fixes jsoncpp redefinition of sprintf due to collision with Windows defines
-flto not added as it breaks the linker with:

Fixes warnings on ignoring return values by (void)function; asserting doesn't help
as they are stripped in release builds and will generate unused variable errors,
in all cases it is presumed the call will not fail.

Undefined dprintf to allow it's redefinition

Per-platform printf format specifiers %u vs %lu and %u vs %ld

error: cannot find -lugin
error: cannot find -lugin-opt=mcpu=generic
error: cannot find -lugin-opt=O0
error: cannot find -lugin-opt=-function-sections
error: cannot find -lugin-opt=-data-sections