COZMO-13139 Include array2d_impl.h for ndk r15b
As noted in cec823a6db, when I upgraded to Android NDK r15b, the release
build broke.  Specifically, for an undefined reference to
'Anki::Array2d<unsigned char>::IsEmpty() const' in
cameraImagingPipeline.cpp.  The debug build worked just fine.  To
workaround this, I found that including array2d_impl.h (where
'inline bool Array2d<T>::IsEmpty() const') is defined fixed the problem.