Tech Debt: Remove include of tofTypes.h from vic-anim process (#5398)
clad/types/tofTypes.h is generated as part of engine clad and shouldn't be used by the vic-anim process.

Fixes erratic build failures reported by mprokos:
victor/animProcess/src/cozmoAnim/animProcessMessages.cpp:43:10: fatal error: 'clad/types/tofTypes.h' file not found [Lexical or Preprocessor Issue]
| #include "clad/types/tofTypes.h"

(cherry picked from commit 15b6c312404015eb3fe444bbfdd9514e56aeadb5)