COZMO-13139 Revert to using Android NDK r14b
When building for Release with Android NDK r15b, there is a link error:

coretech/vision/basestation/src/cameraImagingPipeline.cpp:187: error:
undefined reference to 'Anki::Array2d<unsigned char>::IsEmpty() const'

coretech/vision/basestation/src/cameraImagingPipeline.cpp:258: error:
undefined reference to 'Anki::Array2d<unsigned char>::IsEmpty() const'

Until I can figure out how to fix that, we need to revert to NDK r14b.